version: "2"
virtualmachines:
- name: workstation
  image: instruqt-hashicorp/tfc-workstation-1-0-7
  shell: /bin/bash -l
  machine_type: n1-standard-1
azure_subscriptions:
- name: terraform
  roles:
  - Owner
